image: node:11.14.0
before_script:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash

stages:
  - lint
  - test
  - deploy

.test-os: &test-os
  stage: test
  cache:
    key: "$CI_COMMIT_SHORT_SHA-test"
    paths:
      - .electron-vue/
    policy: pull
  artifacts:
    paths:
     - dist/

eslint:
  stage: lint
  cache:
    key: lint
    paths:
      - node_modules/
      - ~/.yarn
  script:
    - yarn
    - yarn lint
  allow_failure: true

codecov:
  stage: lint
  script:
    - curl -s https://codecov.io/bash -t ${CODECOV_TOKEN} 

windows:
  image: electronuserland/builder:wine
  <<: *test-os
  script: 
    - yarn
    - yarn build:win

linux:
  <<: *test-os
  script: 
    - yarn
    - yarn build:linux

.mac:
  <<: *test-os
  before_script:
    - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install
    - brew install rpm
  script: 
    - yarn
    - yarn build:mac

deploy:
  stage: deploy
  environment: production
  when: manual
  script:
    - yarn
    - yarn build
  only:
    - master
